//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HolyCryptv3.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Reveal : global::System.Configuration.ApplicationSettingsBase {
        
        private static Reveal defaultInstance = ((Reveal)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Reveal())));
        
        public static Reveal Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OutlineWidthStep {
            get {
                return ((int)(this["OutlineWidthStep"]));
            }
            set {
                this["OutlineWidthStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OutlineAlphaStep {
            get {
                return ((int)(this["OutlineAlphaStep"]));
            }
            set {
                this["OutlineAlphaStep"] = value;
            }
        }
    }
}
